name: gardeshpay_app
description: A new Flutter application.
publish_to: "none"

version: 3.9.2+5200

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_id: 0.4.0
  app_settings: 5.1.1
  basic_utils: 5.7.0
  blur: 4.0.0
  camera: 0.10.5+5
  camera_android: 0.10.9+17
  camerawesome:
    path: CamerAwesome
  characters: 1.4.0
  chewie: 1.8.5
  collection: 1.19.1
  connectivity_plus: 6.0.5
  #contacts_service: 0.6.3
  coupon_uikit: 0.2.1
  crypto: 3.0.5
  cupertino_icons: 1.0.8
  device_apps: 2.2.0
  device_info_plus: 11.0.0
  device_preview: 1.2.0
  dio: ^5.8.0+1
  dotted_line: 3.2.2
  dropdown_button2: 2.3.9
  easy_mask: 2.0.1
  easy_refresh: 3.4.0
  encrypt: 5.0.3
  equatable: 2.0.5
  expandable: 5.0.1
  expandable_page_view: 1.0.17
  fast_cached_network_image: ^1.3.2+4
  file_picker: 8.1.2
  file_saver: 0.2.14

  #IOS
  #  firebase_analytics: 11.3.3
  #  firebase_core: 3.6.0
  #  firebase_messaging: 15.1.3

  #Android , web
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5

  #
  fk_user_agent: 2.1.0
  flex_color_scheme: ^8.3.0
  flip_card: 0.7.0
  flutter_downloader: 1.11.8
  flutter_image_compress: 2.3.0
  flutter_image_slideshow:
    path: flutter_image_slideshow
  flutter_inappwebview: 6.1.5
  flutter_launcher_icons: 0.14.1
  flutter_local_notifications: 17.2.3
  flutter_map: 7.0.2
  flutter_pdfview: 1.3.3
  flutter_secure_storage: 9.2.2
  flutter_slidable: 3.1.2
  flutter_sound: 9.28.0
  flutter_speed_dial: 7.0.0
  flutter_spinkit: 5.2.1
  flutter_svg: 2.0.10+1
  get: 4.6.6
  get_storage: 2.1.1
  hand_signature: 3.0.3
  image_cropper: 8.1.0
  image_picker: 1.1.2

  #js: 0.6.7
  latlong2: 0.9.1
  local_auth: 2.3.0
  local_auth_android: 1.0.46
  local_auth_darwin: 1.4.1
  location: 7.0.1
  logger: 2.4.0
  ml_card_scanner:
    path: ml_card_scanner
  mobile_scanner: 5.2.3
  overlay_support: 2.1.0
  otp_plugin:
    path: otp_plugin
  package_info_plus: 8.0.2
  permission_handler: 11.3.1
  persian_datetime_picker:
    path: persian-datetime-picker
  pichak_plugin:
    path: pichak_plugin
  pin_code_fields: ^8.0.1
  pin_input_text_field: 4.5.2
  pointycastle: 3.9.1
  protected_data_available_check:
    path: protected_data_available_check
  safe_device: ^1.2.0
  secure_plugin:
    path: secure_plugin
  sentry_dio: 8.9.0
  sentry_flutter: 8.9.0
  share_plus: 10.1.4
  shared_preferences: 2.3.2
  shimmer: 3.0.0
  smooth_page_indicator: 1.2.0+3
  sms_autofill: 2.4.1
  string_validator: 1.1.0
  syncfusion_flutter_pdf: ^28.2.9
  syncfusion_flutter_sliders: ^28.2.9
  app_links: ^6.3.3
  url_launcher: 6.3.0
  url_launcher_windows: 3.1.2
  util_plugin:
    path: util_plugin
  uuid: 4.5.1
  video_player: 2.9.1
  video_player_android: 2.5.3
  vpn_connection_detector: 1.0.9
  webview_flutter: 4.10.0
  zoom_id:
    path: zoom_id
  #new structure packages
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  injectable_generator: ^2.6.2
  fpdart: ^1.1.1
  flutter_bloc: ^9.1.0
  intl: ^0.20.2
  universal_io: ^2.2.2
  curl_logger_dio_interceptor: ^1.0.0
  fast_rsa: ^3.7.1
  universal_html: ^2.2.4
  melos: ^6.3.2
  path_provider: ^2.1.5
  #flutter_web_plugins:
  #  sdk: flutter
  syncfusion_flutter_pdfviewer: ^28.2.9
  pdf: ^3.11.3
  #web: ^1.0.0
  flutter_native_contact_picker: ^0.0.10
  talker: ^4.7.6
  talker_flutter: ^4.7.6
  talker_bloc_logger: ^4.7.6
  talker_dio_logger: ^4.7.6
  flutter_localizations:
    sdk: flutter
  dashed_circular_progress_bar: ^0.0.6
  flutter_contacts: ^1.1.9+2
  http: ^1.4.0
  draggable_panel: ^1.3.1




dependency_overrides:
  webview_flutter_android: 3.16.9
  #web: ^1.0.0
  intl: ^0.19.0


dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  #new structure package :
  freezed: ^2.2.0
  json_serializable: any
  #dart_code_metrics: ^4.16.0


flutter_icons:
  image_path: 'assets/images/logo.png'
  android: true
  ios: false

flutter_intl: # add this lineSM-A037F
  enabled: true # add this line
# The following section is specific to Flutter.w
flutter:
  generate: true

  assets:
    - assets/menuWeb.json
    - assets/images/
    - assets/icons/
    - assets/json/
    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm

  uses-material-design: true
  fonts:
    - family: IranYekan
      fonts:
        - asset: fonts/IRANYekanMobileRegular.ttf
        - asset: fonts/IRANYekanMobileMedium.ttf
          weight: 500
        - asset: fonts/IRANYekanMobileBold.ttf
          weight: 700
        - asset: fonts/IRANYekanMobileExtraBold.ttf
          weight: 900